site_name: Knowledge
site_url: https://whiskeysierra.github.io/knowledge

nav: [ ]

repo_url: https://github.com/whiskeysierra/knowledge
repo_name: Edit on Github
edit_uri: ?path=/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite
  - footnotes
  - plantuml_markdown:
      format: svg_inline
      cachedir: plantuml/.cache
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized
  - include-markdown
  - search
