site_name: Knowledge
site_url: https://whiskeysierra.github.io/knowledge

nav:
  - Concepts & Principles:
      - concepts-and-principles/index.md
      - Composition: concepts-and-principles/composition.md
      - Compile Time vs Runtime: concepts-and-principles/compile-time-runtime.md
  - Patterns:
      - patterns/index.md
      - Composite: patterns/composite.md
      - Primitive Obsession: patterns/primitive-obsession.md
      - Staged Builders: patterns/staged-builders.md
      - Test Contract: patterns/test-contract.md
      - Time Dependent: patterns/time-dependent.md
  - Practices:
      - practices/index.md
      - Hand Roll Test Doubles: practices/hand-roll-test-doubles.md

repo_url: https://github.com/whiskeysierra/knowledge
repo_name: Edit on Github
edit_uri: ?path=/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes

not_in_nav: |
  /index.md
  /tags.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite
  - footnotes
  - plantuml_markdown:
      format: svg_inline
      cachedir: plantuml/.cache
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized
  - include-markdown:
      start: "//"
  - search
  - tags
